//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_for_sber.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id_group { get; set; }
        public string title_product { get; set; }
        public int id_product { get; set; }
    
        public virtual group group { get; set; }
    }
}
